### PR TITLE
More detailed README

### PR DESCRIPTION
**Pull request by mathwhiz1212**
I like more detailed readmes so I created one. If you like it, please use it. If not, don't.

### CODE REVIEW

**Comment by mathwhiz1212** [comment]
Nevermind my readme needs a little more work before it is a proper readme.

**Comment by mathwhiz1212** [comment]
Now it is a proper readme.

**Comment by coolaj86** [comment]
Note: In markdown:

```
<h1> is `#` or `===`
<h2> is `##` or `---`
<h3> is `###`
<h4> is `####`
... and so on
```

**Comment by mathwhiz1212** [comment]
Thanks! I didn't know that. This was my first experience with markdown aside from the main title having a # in front.

**Pull request merged**
